### ISSUE TITLE
Error when running test data

### ISSUE THREAD

**Issue by hubner-lab** [TPPSellinger/eSMC#1]
hello, 
 I've encountered an error when trying to run the test

**Error in BB::BBoptim(c(oldrho, oldbeta, oldsigma, oldXi_), function_to_minimize_optim,  : 
  All calls to spg failed. Last error: Error in spg(par = par, fn = fn, gr = gr, method = cpars[1], project = project,  : 
  Failure in initial function evaluation!Error in x:xx : NA/NaN argument

Calls: eSMC -> Baum_Welch_algo -> <Anonymous>
In addition: Warning message:
In if (gamma_ != (gamma * beta * 2 * (1 - sigma)/(2 - sigma))) { :
  the condition has length > 1 and only the first element will be used
Execution halted**

**Comment by TPPSellinger** [comment]
This is an error I already encountered. This error comes from the package BB which I use to optimize the expected likelihood. The function is unable to optimize the expected likelihood and there can be different explanation for this. I updated the package since intial release which fixes some small bug, I would first suggest for you to check you have the latest version.

Concerning the error, I would suggest you to change the number of hidden states (to 30 for example). You can also set BoxP=c(2,2) and/or analyze chrosomome/scaffold independently (i.e. NC=1). This should normally fix the problem. You can also chose other set of parameters, it should also solve problem as you might just be unlucky when optimizing the likelihood.

However, there is a chance that it does not fix the problem. I noticed when underlying hypothesis are violated, it is not possible to optimize likelihood (because model is not valid).  Something not accounted by the model might be driving the genome structure, making it impossible to optimize likelihood. You can check if any hypothesis might be violated (TEs, population structure, selection sequencing quality, etc ). I would suggest to run the method only on scaffolds where you think hypothesis are not too violated (or less likeli). For example, you can check to distribution of SNPs along the genome and check if anything looks strange.

I would also suggest to use MSMC2, MSMC or PSMC'  and post process the results to estimate selfing using the formulas of the paper. As they don't optimize under constraint they might be less likeli to crash. 

I hope this can help you. Let me know if you have any other issue.
